name: Command via SSH

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: create folder via OPEN SSH Private Key
        uses: bubeph/test-ci-cd@master
        with:
          command:             
            # cd ci-cd.bubeph.com && mkdir folder-test
            git clone git@github.com:bubeph/test-ci-cd.git@master                      
          #repository: bubeph/test-ci-cd@master
          host: ci-cd.bubeph.com
          # server161s.web-hosting.com
          port: 21098
          # path: /home
          username: bubexctm
          # password: ddZiTOArK.3r
          passphrase: ddZiTOArK.3r
          privateKey: ${{ secrets.KEY_PASS_SSH }}
          #timeout: 60000          
          # add comment 
          #script: |
          #  cd ci-cd.bubeph.com && mkdir folder-test
        env:
          CI: true
      #- name: create another folder 
      #  run: cd ci-cd.bubeph.com && mkdir folder-test
        
          
