name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: ssh pipeline 
      uses: actions/checkout@v2
      # uses: bubeph/test-ci-cd@master
      env:        
        DIR2: "test-folder"
      with:        
        repository: bubeph/test-ci-cd
        host: ci-cd.bubeph.com
        # ssh-known-hosts: server161.web-hosting.com
        user: bubexctm
        pass: ddZiTOArK.3r
        # ssh-key: ${{ secrets.SSH-KEY-CI-CD }}
        port: 21098
        connect_timeout: 20s
        script: |                 
          mkdir "test-folder"