name: Command via SSH

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ls -a via OPEN SSH Private Key
        uses: bubeph/test-ci-cd@master
        with:
          command: ls -a
          host: server161s.web-hosting.com
          port: 21098
          path: /home
          username: bubexctm
          # password: ddZiTOArK.3r
          passphrase: ddZiTOArK.3r
          privateKey: ${{ secrets.KEY_PASS_SSH }}
          #timeout: 60000          
          # add comment 
        env:
          CI: true
