name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: ssh pipeline 
      uses: actions/checkout@v2
      # uses: bubeph/test-ci-cd@master
      env:
        WELCOME: "ssh pipeline"
        DIR2: "ci-cd.bubeph.com/test-folder"
      with:        
        host: server161.web-hosting.com
        user: bubexctm 
        pass: ddZiTOArK.3r
        port:  21098
        connect_timeout: 20s
        #script: |
        #  echo $WELCOME
        #  mkdir -p $DIR2